/* Write your PL/SQL query statement below */
SELECT EMPLOYEE_ID, 
CASE 
	WHEN NAME NOT LIKE 'M%' AND MOD(EMPLOYEE_ID,2) <> 0 THEN SALARY 
	ELSE 0 
	END AS BONUS 
FROM EMPLOYEES 
ORDER BY EMPLOYEE_ID;
